##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

# -- THIS FILE IS AUTO-GENERATED -- 

mpi_sources += \
    src/binding/c/attr/attr_delete.c \
    src/binding/c/attr/attr_get.c \
    src/binding/c/attr/attr_put.c \
    src/binding/c/attr/comm_create_keyval.c \
    src/binding/c/attr/comm_delete_attr.c \
    src/binding/c/attr/comm_free_keyval.c \
    src/binding/c/attr/comm_get_attr.c \
    src/binding/c/attr/comm_set_attr.c \
    src/binding/c/attr/keyval_create.c \
    src/binding/c/attr/keyval_free.c \
    src/binding/c/attr/type_create_keyval.c \
    src/binding/c/attr/type_delete_attr.c \
    src/binding/c/attr/type_free_keyval.c \
    src/binding/c/attr/type_get_attr.c \
    src/binding/c/attr/type_set_attr.c \
    src/binding/c/attr/win_create_keyval.c \
    src/binding/c/attr/win_delete_attr.c \
    src/binding/c/attr/win_free_keyval.c \
    src/binding/c/attr/win_get_attr.c \
    src/binding/c/attr/win_set_attr.c \
    src/binding/c/coll/allgather.c \
    src/binding/c/coll/allgather_init.c \
    src/binding/c/coll/allgatherv.c \
    src/binding/c/coll/allgatherv_init.c \
    src/binding/c/coll/allreduce.c \
    src/binding/c/coll/allreduce_init.c \
    src/binding/c/coll/alltoall.c \
    src/binding/c/coll/alltoall_init.c \
    src/binding/c/coll/alltoallv.c \
    src/binding/c/coll/alltoallv_init.c \
    src/binding/c/coll/alltoallw.c \
    src/binding/c/coll/alltoallw_init.c \
    src/binding/c/coll/barrier.c \
    src/binding/c/coll/barrier_init.c \
    src/binding/c/coll/bcast.c \
    src/binding/c/coll/bcast_init.c \
    src/binding/c/coll/exscan.c \
    src/binding/c/coll/exscan_init.c \
    src/binding/c/coll/gather.c \
    src/binding/c/coll/gather_init.c \
    src/binding/c/coll/gatherv.c \
    src/binding/c/coll/gatherv_init.c \
    src/binding/c/coll/iallgather.c \
    src/binding/c/coll/iallgatherv.c \
    src/binding/c/coll/iallreduce.c \
    src/binding/c/coll/ialltoall.c \
    src/binding/c/coll/ialltoallv.c \
    src/binding/c/coll/ialltoallw.c \
    src/binding/c/coll/ibarrier.c \
    src/binding/c/coll/ibcast.c \
    src/binding/c/coll/iexscan.c \
    src/binding/c/coll/igather.c \
    src/binding/c/coll/igatherv.c \
    src/binding/c/coll/ineighbor_allgather.c \
    src/binding/c/coll/ineighbor_allgatherv.c \
    src/binding/c/coll/ineighbor_alltoall.c \
    src/binding/c/coll/ineighbor_alltoallv.c \
    src/binding/c/coll/ineighbor_alltoallw.c \
    src/binding/c/coll/ireduce.c \
    src/binding/c/coll/ireduce_scatter.c \
    src/binding/c/coll/ireduce_scatter_block.c \
    src/binding/c/coll/iscan.c \
    src/binding/c/coll/iscatter.c \
    src/binding/c/coll/iscatterv.c \
    src/binding/c/coll/neighbor_allgather.c \
    src/binding/c/coll/neighbor_allgather_init.c \
    src/binding/c/coll/neighbor_allgatherv.c \
    src/binding/c/coll/neighbor_allgatherv_init.c \
    src/binding/c/coll/neighbor_alltoall.c \
    src/binding/c/coll/neighbor_alltoall_init.c \
    src/binding/c/coll/neighbor_alltoallv.c \
    src/binding/c/coll/neighbor_alltoallv_init.c \
    src/binding/c/coll/neighbor_alltoallw.c \
    src/binding/c/coll/neighbor_alltoallw_init.c \
    src/binding/c/coll/reduce.c \
    src/binding/c/coll/reduce_init.c \
    src/binding/c/coll/reduce_local.c \
    src/binding/c/coll/reduce_scatter.c \
    src/binding/c/coll/reduce_scatter_block.c \
    src/binding/c/coll/reduce_scatter_block_init.c \
    src/binding/c/coll/reduce_scatter_init.c \
    src/binding/c/coll/scan.c \
    src/binding/c/coll/scan_init.c \
    src/binding/c/coll/scatter.c \
    src/binding/c/coll/scatter_init.c \
    src/binding/c/coll/scatterv.c \
    src/binding/c/coll/scatterv_init.c \
    src/binding/c/comm/comm_compare.c \
    src/binding/c/comm/comm_create.c \
    src/binding/c/comm/comm_create_group.c \
    src/binding/c/comm/comm_dup.c \
    src/binding/c/comm/comm_dup_with_info.c \
    src/binding/c/comm/comm_free.c \
    src/binding/c/comm/comm_get_info.c \
    src/binding/c/comm/comm_get_name.c \
    src/binding/c/comm/comm_group.c \
    src/binding/c/comm/comm_idup.c \
    src/binding/c/comm/comm_idup_with_info.c \
    src/binding/c/comm/comm_rank.c \
    src/binding/c/comm/comm_remote_group.c \
    src/binding/c/comm/comm_remote_size.c \
    src/binding/c/comm/comm_set_info.c \
    src/binding/c/comm/comm_set_name.c \
    src/binding/c/comm/comm_size.c \
    src/binding/c/comm/comm_split.c \
    src/binding/c/comm/comm_split_type.c \
    src/binding/c/comm/comm_test_inter.c \
    src/binding/c/comm/intercomm_create.c \
    src/binding/c/comm/intercomm_create_from_groups.c \
    src/binding/c/comm/intercomm_merge.c \
    src/binding/c/comm/comm_revoke.c \
    src/binding/c/comm/comm_shrink.c \
    src/binding/c/comm/comm_failure_ack.c \
    src/binding/c/comm/comm_failure_get_acked.c \
    src/binding/c/comm/comm_agree.c \
    src/binding/c/datatype/get_address.c \
    src/binding/c/datatype/get_count.c \
    src/binding/c/datatype/get_elements.c \
    src/binding/c/datatype/get_elements_x.c \
    src/binding/c/datatype/pack.c \
    src/binding/c/datatype/pack_external.c \
    src/binding/c/datatype/pack_external_size.c \
    src/binding/c/datatype/pack_size.c \
    src/binding/c/datatype/status_set_elements.c \
    src/binding/c/datatype/status_set_elements_x.c \
    src/binding/c/datatype/type_commit.c \
    src/binding/c/datatype/type_contiguous.c \
    src/binding/c/datatype/type_create_darray.c \
    src/binding/c/datatype/type_create_hindexed.c \
    src/binding/c/datatype/type_create_hindexed_block.c \
    src/binding/c/datatype/type_create_hvector.c \
    src/binding/c/datatype/type_create_indexed_block.c \
    src/binding/c/datatype/type_create_resized.c \
    src/binding/c/datatype/type_create_struct.c \
    src/binding/c/datatype/type_create_subarray.c \
    src/binding/c/datatype/type_dup.c \
    src/binding/c/datatype/type_free.c \
    src/binding/c/datatype/type_get_contents.c \
    src/binding/c/datatype/type_get_envelope.c \
    src/binding/c/datatype/type_get_extent.c \
    src/binding/c/datatype/type_get_extent_x.c \
    src/binding/c/datatype/type_get_name.c \
    src/binding/c/datatype/type_get_true_extent.c \
    src/binding/c/datatype/type_get_true_extent_x.c \
    src/binding/c/datatype/type_indexed.c \
    src/binding/c/datatype/type_match_size.c \
    src/binding/c/datatype/type_set_name.c \
    src/binding/c/datatype/type_size.c \
    src/binding/c/datatype/type_size_x.c \
    src/binding/c/datatype/type_vector.c \
    src/binding/c/datatype/unpack.c \
    src/binding/c/datatype/unpack_external.c \
    src/binding/c/datatype/address.c \
    src/binding/c/datatype/type_extent.c \
    src/binding/c/datatype/type_lb.c \
    src/binding/c/datatype/type_ub.c \
    src/binding/c/datatype/type_hindexed.c \
    src/binding/c/datatype/type_hvector.c \
    src/binding/c/datatype/type_struct.c \
    src/binding/c/errhan/add_error_class.c \
    src/binding/c/errhan/add_error_code.c \
    src/binding/c/errhan/add_error_string.c \
    src/binding/c/errhan/comm_call_errhandler.c \
    src/binding/c/errhan/comm_create_errhandler.c \
    src/binding/c/errhan/comm_get_errhandler.c \
    src/binding/c/errhan/comm_set_errhandler.c \
    src/binding/c/errhan/errhandler_free.c \
    src/binding/c/errhan/error_class.c \
    src/binding/c/errhan/error_string.c \
    src/binding/c/errhan/file_call_errhandler.c \
    src/binding/c/errhan/file_create_errhandler.c \
    src/binding/c/errhan/file_get_errhandler.c \
    src/binding/c/errhan/file_set_errhandler.c \
    src/binding/c/errhan/session_call_errhandler.c \
    src/binding/c/errhan/session_create_errhandler.c \
    src/binding/c/errhan/session_get_errhandler.c \
    src/binding/c/errhan/session_set_errhandler.c \
    src/binding/c/errhan/win_call_errhandler.c \
    src/binding/c/errhan/win_create_errhandler.c \
    src/binding/c/errhan/win_get_errhandler.c \
    src/binding/c/errhan/win_set_errhandler.c \
    src/binding/c/errhan/delete_error_class.c \
    src/binding/c/errhan/delete_error_code.c \
    src/binding/c/errhan/delete_error_string.c \
    src/binding/c/errhan/errhandler_create.c \
    src/binding/c/errhan/errhandler_get.c \
    src/binding/c/errhan/errhandler_set.c \
    src/binding/c/group/group_compare.c \
    src/binding/c/group/group_difference.c \
    src/binding/c/group/group_excl.c \
    src/binding/c/group/group_free.c \
    src/binding/c/group/group_incl.c \
    src/binding/c/group/group_intersection.c \
    src/binding/c/group/group_range_excl.c \
    src/binding/c/group/group_range_incl.c \
    src/binding/c/group/group_rank.c \
    src/binding/c/group/group_size.c \
    src/binding/c/group/group_translate_ranks.c \
    src/binding/c/group/group_union.c \
    src/binding/c/info/info_create.c \
    src/binding/c/info/info_create_env.c \
    src/binding/c/info/info_delete.c \
    src/binding/c/info/info_dup.c \
    src/binding/c/info/info_free.c \
    src/binding/c/info/info_get.c \
    src/binding/c/info/info_get_nkeys.c \
    src/binding/c/info/info_get_nthkey.c \
    src/binding/c/info/info_get_string.c \
    src/binding/c/info/info_get_valuelen.c \
    src/binding/c/info/info_set.c \
    src/binding/c/init/abort.c \
    src/binding/c/init/comm_create_from_group.c \
    src/binding/c/init/finalize.c \
    src/binding/c/init/finalized.c \
    src/binding/c/init/group_from_session_pset.c \
    src/binding/c/init/init.c \
    src/binding/c/init/init_thread.c \
    src/binding/c/init/initialized.c \
    src/binding/c/init/is_thread_main.c \
    src/binding/c/init/query_thread.c \
    src/binding/c/init/session_finalize.c \
    src/binding/c/init/session_get_info.c \
    src/binding/c/init/session_get_nth_pset.c \
    src/binding/c/init/session_get_num_psets.c \
    src/binding/c/init/session_get_pset_info.c \
    src/binding/c/init/session_init.c \
    src/binding/c/misc/aint_add.c \
    src/binding/c/misc/aint_diff.c \
    src/binding/c/misc/get_library_version.c \
    src/binding/c/misc/get_processor_name.c \
    src/binding/c/misc/get_version.c \
    src/binding/c/misc/pcontrol.c \
    src/binding/c/misc/gpu_query_support.c \
    src/binding/c/misc/query_cuda_support.c \
    src/binding/c/misc/query_ze_support.c \
    src/binding/c/misc/query_hip_support.c \
    src/binding/c/mpit/category_changed.c \
    src/binding/c/mpit/category_get_categories.c \
    src/binding/c/mpit/category_get_cvars.c \
    src/binding/c/mpit/category_get_events.c \
    src/binding/c/mpit/category_get_index.c \
    src/binding/c/mpit/category_get_info.c \
    src/binding/c/mpit/category_get_num.c \
    src/binding/c/mpit/category_get_num_events.c \
    src/binding/c/mpit/category_get_pvars.c \
    src/binding/c/mpit/cvar_get_index.c \
    src/binding/c/mpit/cvar_get_info.c \
    src/binding/c/mpit/cvar_get_num.c \
    src/binding/c/mpit/cvar_handle_alloc.c \
    src/binding/c/mpit/cvar_handle_free.c \
    src/binding/c/mpit/cvar_read.c \
    src/binding/c/mpit/cvar_write.c \
    src/binding/c/mpit/enum_get_info.c \
    src/binding/c/mpit/enum_get_item.c \
    src/binding/c/mpit/event_callback_get_info.c \
    src/binding/c/mpit/event_callback_set_info.c \
    src/binding/c/mpit/event_copy.c \
    src/binding/c/mpit/event_get_index.c \
    src/binding/c/mpit/event_get_info.c \
    src/binding/c/mpit/event_get_num.c \
    src/binding/c/mpit/event_get_source.c \
    src/binding/c/mpit/event_get_timestamp.c \
    src/binding/c/mpit/event_handle_alloc.c \
    src/binding/c/mpit/event_handle_free.c \
    src/binding/c/mpit/event_handle_get_info.c \
    src/binding/c/mpit/event_handle_set_info.c \
    src/binding/c/mpit/event_read.c \
    src/binding/c/mpit/event_register_callback.c \
    src/binding/c/mpit/event_set_dropped_handler.c \
    src/binding/c/mpit/finalize.c \
    src/binding/c/mpit/init_thread.c \
    src/binding/c/mpit/pvar_get_index.c \
    src/binding/c/mpit/pvar_get_info.c \
    src/binding/c/mpit/pvar_get_num.c \
    src/binding/c/mpit/pvar_handle_alloc.c \
    src/binding/c/mpit/pvar_handle_free.c \
    src/binding/c/mpit/pvar_read.c \
    src/binding/c/mpit/pvar_readreset.c \
    src/binding/c/mpit/pvar_reset.c \
    src/binding/c/mpit/pvar_session_create.c \
    src/binding/c/mpit/pvar_session_free.c \
    src/binding/c/mpit/pvar_start.c \
    src/binding/c/mpit/pvar_stop.c \
    src/binding/c/mpit/pvar_write.c \
    src/binding/c/mpit/source_get_info.c \
    src/binding/c/mpit/source_get_num.c \
    src/binding/c/mpit/source_get_timestamp.c \
    src/binding/c/op/op_commutative.c \
    src/binding/c/op/op_create.c \
    src/binding/c/op/op_free.c \
    src/binding/c/part/parrived.c \
    src/binding/c/part/pready.c \
    src/binding/c/part/pready_list.c \
    src/binding/c/part/pready_range.c \
    src/binding/c/part/precv_init.c \
    src/binding/c/part/psend_init.c \
    src/binding/c/pt2pt/bsend.c \
    src/binding/c/pt2pt/bsend_init.c \
    src/binding/c/pt2pt/buffer_attach.c \
    src/binding/c/pt2pt/buffer_detach.c \
    src/binding/c/pt2pt/ibsend.c \
    src/binding/c/pt2pt/improbe.c \
    src/binding/c/pt2pt/imrecv.c \
    src/binding/c/pt2pt/iprobe.c \
    src/binding/c/pt2pt/irecv.c \
    src/binding/c/pt2pt/irsend.c \
    src/binding/c/pt2pt/isend.c \
    src/binding/c/pt2pt/isendrecv.c \
    src/binding/c/pt2pt/isendrecv_replace.c \
    src/binding/c/pt2pt/issend.c \
    src/binding/c/pt2pt/mprobe.c \
    src/binding/c/pt2pt/mrecv.c \
    src/binding/c/pt2pt/probe.c \
    src/binding/c/pt2pt/recv.c \
    src/binding/c/pt2pt/recv_init.c \
    src/binding/c/pt2pt/rsend.c \
    src/binding/c/pt2pt/rsend_init.c \
    src/binding/c/pt2pt/send.c \
    src/binding/c/pt2pt/send_init.c \
    src/binding/c/pt2pt/sendrecv.c \
    src/binding/c/pt2pt/sendrecv_replace.c \
    src/binding/c/pt2pt/ssend.c \
    src/binding/c/pt2pt/ssend_init.c \
    src/binding/c/request/cancel.c \
    src/binding/c/request/grequest_complete.c \
    src/binding/c/request/grequest_start.c \
    src/binding/c/request/request_free.c \
    src/binding/c/request/request_get_status.c \
    src/binding/c/request/start.c \
    src/binding/c/request/startall.c \
    src/binding/c/request/status_set_cancelled.c \
    src/binding/c/request/test.c \
    src/binding/c/request/test_cancelled.c \
    src/binding/c/request/testall.c \
    src/binding/c/request/testany.c \
    src/binding/c/request/testsome.c \
    src/binding/c/request/wait.c \
    src/binding/c/request/waitall.c \
    src/binding/c/request/waitany.c \
    src/binding/c/request/waitsome.c \
    src/binding/c/request/grequest_start_x.c \
    src/binding/c/request/grequest_class_create.c \
    src/binding/c/request/grequest_class_allocate.c \
    src/binding/c/rma/accumulate.c \
    src/binding/c/rma/alloc_mem.c \
    src/binding/c/rma/compare_and_swap.c \
    src/binding/c/rma/fetch_and_op.c \
    src/binding/c/rma/free_mem.c \
    src/binding/c/rma/get.c \
    src/binding/c/rma/get_accumulate.c \
    src/binding/c/rma/put.c \
    src/binding/c/rma/raccumulate.c \
    src/binding/c/rma/rget.c \
    src/binding/c/rma/rget_accumulate.c \
    src/binding/c/rma/rput.c \
    src/binding/c/rma/win_allocate.c \
    src/binding/c/rma/win_allocate_shared.c \
    src/binding/c/rma/win_attach.c \
    src/binding/c/rma/win_complete.c \
    src/binding/c/rma/win_create.c \
    src/binding/c/rma/win_create_dynamic.c \
    src/binding/c/rma/win_detach.c \
    src/binding/c/rma/win_fence.c \
    src/binding/c/rma/win_flush.c \
    src/binding/c/rma/win_flush_all.c \
    src/binding/c/rma/win_flush_local.c \
    src/binding/c/rma/win_flush_local_all.c \
    src/binding/c/rma/win_free.c \
    src/binding/c/rma/win_get_group.c \
    src/binding/c/rma/win_get_info.c \
    src/binding/c/rma/win_get_name.c \
    src/binding/c/rma/win_lock.c \
    src/binding/c/rma/win_lock_all.c \
    src/binding/c/rma/win_post.c \
    src/binding/c/rma/win_set_info.c \
    src/binding/c/rma/win_set_name.c \
    src/binding/c/rma/win_shared_query.c \
    src/binding/c/rma/win_start.c \
    src/binding/c/rma/win_sync.c \
    src/binding/c/rma/win_test.c \
    src/binding/c/rma/win_unlock.c \
    src/binding/c/rma/win_unlock_all.c \
    src/binding/c/rma/win_wait.c \
    src/binding/c/spawn/close_port.c \
    src/binding/c/spawn/comm_accept.c \
    src/binding/c/spawn/comm_connect.c \
    src/binding/c/spawn/comm_disconnect.c \
    src/binding/c/spawn/comm_get_parent.c \
    src/binding/c/spawn/comm_join.c \
    src/binding/c/spawn/comm_spawn.c \
    src/binding/c/spawn/comm_spawn_multiple.c \
    src/binding/c/spawn/lookup_name.c \
    src/binding/c/spawn/open_port.c \
    src/binding/c/spawn/publish_name.c \
    src/binding/c/spawn/unpublish_name.c \
    src/binding/c/timer/wtick.c \
    src/binding/c/timer/wtime.c \
    src/binding/c/topo/cart_coords.c \
    src/binding/c/topo/cart_create.c \
    src/binding/c/topo/cart_get.c \
    src/binding/c/topo/cart_map.c \
    src/binding/c/topo/cart_rank.c \
    src/binding/c/topo/cart_shift.c \
    src/binding/c/topo/cart_sub.c \
    src/binding/c/topo/cartdim_get.c \
    src/binding/c/topo/dims_create.c \
    src/binding/c/topo/dist_graph_create.c \
    src/binding/c/topo/dist_graph_create_adjacent.c \
    src/binding/c/topo/dist_graph_neighbors.c \
    src/binding/c/topo/dist_graph_neighbors_count.c \
    src/binding/c/topo/graph_create.c \
    src/binding/c/topo/graph_get.c \
    src/binding/c/topo/graph_map.c \
    src/binding/c/topo/graph_neighbors.c \
    src/binding/c/topo/graph_neighbors_count.c \
    src/binding/c/topo/graphdims_get.c \
    src/binding/c/topo/topo_test.c
